### PR TITLE
Increase number of cats to over 9000

### PR DESCRIPTION
**Pull request by rghvdberg**

### CODE REVIEW

**Comment by CactiChameleon9** [comment]
I see no problems with the following PR, however the formatting of the git message is not sufficient.

**Comment by rghvdberg** [comment]
sorry about the 900 typo

**Comment by CactiChameleon9** [comment]
Do not make a new PR, I will attempt to amend

**Comment by CactiChameleon9** [comment]
@rghvdberg You have updated the script, but I would be much more pleased if the readme was updated also

**Pull request merged**
